modules/admin/models/Article.php
<?php

namespace app\modules\admin\models;

use app\modules\admin\Module;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\SluggableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\StringHelper;

/**
 * This is the model class for table "article".
 *
 * @property integer $id
 * @property string $slug
 * @property string $title
 * @property string $body
 * @property string $view
 * @property integer $category_id
 * @property string $thumbnail_base_url
 * @property string $thumbnail_path
 * @property integer $author_id
 * @property integer $updater_id
 * @property integer $status
 * @property integer $published_at
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property ArticleCategory $category
 * @property User $author
 * @property User $updater
 * @property ArticleAttachment[] $articleAttachments
 */
class Article extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::class,
                'attribute' => 'title',
                'immutable' => true,
                'ensureUnique' => true
            ],
            [
                'class' => BlameableBehavior::class,
                'createdByAttribute' => 'author_id',
                'updatedByAttribute' => 'author_id'

            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'body', 'createdAt'], 'required'],
            [['body', 'createdAt'], 'string'],
            [['category_id', 'author_id', 'updater_id', 'status', 'published_at', 'created_at', 'updated_at'], 'integer'],
            [['slug', 'thumbnail_base_url', 'thumbnail_path'], 'string', 'max' => 1024],
            ['slug', 'match', 'pattern' => '/^[0-9a-zA-Z_-]+$/',
                'message' => 'Допускаются только буквы латинского алфавита, тире и нижнее подчеркивание'],
            [['title'], 'string', 'max' => 512],
            [['view'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Module::t('app', 'ID'),
            'slug' => 'Псевдоним',
            'title' => Module::t('app', 'Title'),
            'body' => Module::t('app', 'Body'),
            'view' => Module::t('app', 'View'),
            'category_id' => Module::t('app', 'Category ID'),
            'thumbnail_base_url' => Module::t('app', 'Thumbnail Base Url'),
            'thumbnail_path' => Module::t('app', 'Thumbnail Path'),
            'author_id' => Module::t('app', 'Author ID'),
            'updater_id' => Module::t('app', 'Updater ID'),
            'status' => Module::t('app', 'Status'),
            'published_at' => Module::t('app', 'Published At'),
            'created_at' => Module::t('app', 'Created At'),
            'createdAt' => 'Дата публикации',
            'updated_at' => Module::t('app', 'Updated At'),
        ];
    }

    /**
     * @return false|string
     */
    public function getCreatedAt()
    {
        return $this->created_at ? date('d.m.Y', $this->created_at) : date('d.m.Y');
    }

    /**
     * @param $date
     */
    public function setCreatedAt($date)
    {
        $this->created_at = strtotime($date);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(ArticleCategory::class, ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(User::class, ['id' => 'author_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdater()
    {
        return $this->hasOne(User::class, ['id' => 'updater_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticleAttachments()
    {
        return $this->hasMany(ArticleAttachment::class, ['article_id' => 'id']);
    }

    /**
     * @param $category
     * @param null $limit
     * @param int $order
     * @return $this
     */
    public static function getByCategory($category, $limit = null, $order = SORT_DESC)
    {
        $categoryId = ArticleCategory::getIdBySlug($category);
        $query = self::find()->where(['category_id' => $categoryId])->orderBy(['id' => $order]);
        if ($limit) {
            $query->limit($limit);
        }
        return $query->all();
    }

    /**
     * @return array
     */
    public static function slideHistory()
    {
        $items = self::getByCategory('history', null, SORT_ASC);
        $slides = [];
        foreach ($items as $i => $item) {
            $number = Html::tag('div', $i + 1, ['class' => 'history-number']);
            $title = Html::tag('div', $item->title, ['class' => 'history-title']);
            $body = Html::tag('div', $item->body, ['class' => 'history-body']);
            $text = Html::tag('div', $number . $title . $body, ['class' => 'history-text']);
            $image = Html::tag('div', Html::img($item->thumbnail_path) . $text, ['class' => 'history-image']);

            $slides[] = Html::tag('div', $image, ['class' => 'history-box']);
        }
        return $slides;
    }

    /**
     * @return array
     */
    public static function slideEquipment()
    {
        $items = self::getByCategory('equipment');
        $slides = [];
        foreach ($items as $item) {
            $avatar = Html::tag('div', Html::img($item->thumbnail_path), ['class' => 'card-avatar']);
            $header = Html::tag('div', $avatar, ['class' => 'card-header']);
            $body = Html::tag('div', $item->title, ['class' => 'card-body']);
            $button = Html::button('Подробнее', [
                'data-toggle' => 'modal',
                'data-target' => '#modalCard',
                'data-id' => $item->id,
                'data-title' => $item->title
            ]);
            $footer = Html::tag('div', $button, ['class' => 'card-footer']);

            $slides[] = Html::tag('div', $header . $body . $footer, ['class' => 'card-md card-black']);
        }
        return $slides;
    }

    /**
     * @return array
     */
    public static function slideBranches()
    {
        $urls = [
            'itc' => '#',
            'baks' => 'https://bacs-tech.ru',
            'promyslennye-tehnologii' => 'http://www.pmtn.ru',
            'gazfleksizol' => '#',
            'centr-ekspertizy' => 'http://expertiza-omsk.ru',
            'specstrojlogistika' => 'https://specsl.pulscen.ru',
            'specpromizolacia' => 'http://спи-омск.рф',
            'nppspecteh' => 'http://спецтехомск.рф'
        ];
        $items = self::getByCategory('branches');
        $slides = [];
        /** @var Article $item */
        foreach ($items as $item) {
            $title = Html::tag('div', $item->title, ['class' => 'card-title']);
            $header = Html::tag('div', $title, ['class' => 'card-header']);
            $body = Html::tag('div', $item->body, ['class' => 'card-body']);
            $button = Html::a('<i class="fa fa-external-link"></i> Подробнее',
                ArrayHelper::getValue($urls, $item->slug, '#'), ['target' => '_blank']);
            $footer = Html::tag('div', $button, ['class' => 'card-footer']);

            $slides[] = Html::tag('div', $header . $body . $footer, ['class' => 'card-sm']);
        }
        return $slides;
    }
}

modules/admin/controllers/ArticleController.php
<?php

namespace app\modules\admin\controllers;

use app\modules\admin\models\ArticleCategory;
use Yii;
use app\modules\admin\models\Article;
use app\modules\admin\models\ArticleSearch;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->sort = ['defaultOrder' => ['id' => SORT_DESC]];
        $categories = ArticleCategory::find()->asArray()->all();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'categories' => ArrayHelper::map($categories, 'id', 'title')
        ]);
    }

    /**
     * Displays a single Article model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Article();
        $categories = ArticleCategory::find()->asArray()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $action = Yii::$app->request->post('action', 'save');
            if ($action === 'save') {
                return $this->redirect(['index']);
            } else {
                return $this->redirect(['update', 'id' => $model->id]);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
                'categories' => ArrayHelper::map($categories, 'id', 'title')
            ]);
        }
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $categories = ArticleCategory::find()->asArray()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $action = Yii::$app->request->post('action', 'save');
            if ($action === 'save') {
                return $this->redirect(['index']);
            } else {
                return $this->redirect(['update', 'id' => $model->id]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
                'categories' => ArrayHelper::map($categories, 'id', 'title')
            ]);
        }
    }

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/admin/views/article/_form.php
<?php

use app\modules\admin\widgets\ButtonGroup;
use mihaildev\ckeditor\CKEditor;
use mihaildev\elfinder\InputFile;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\elfinder\ElFinder;
use yii\widgets\MaskedInput;

/**
 * @var $this yii\web\View
 * @var $model app\modules\admin\models\Article
 * @var $form yii\widgets\ActiveForm
 * @var $categories \app\modules\admin\models\ArticleCategory[]
 */
?>

<div class="article-form">
    <?php $form = ActiveForm::begin(); ?>
  <div class="panel panel-default">
    <div class="panel-heading">
        <?= Html::submitButton('Применить', ['class' => 'btn btn-primary', 'name' => 'action', 'value' => 'apply']) ?>
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success', 'name' => 'action', 'value' => 'save']) ?>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-2"><?= $form->field($model, 'createdAt')
                ->widget(MaskedInput::class, ['mask' => '99.99.9999', 'options' => ['placeholder' => 'ДД.ММ.ГГГГ']]) ?></div>
        <div
            class="col-md-2"><?= $form->field($model, 'category_id')->dropDownList($categories, ['prompt' => '']) ?></div>
        <div class="col-md-4"><?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?></div>
        <div class="col-md-4"><?= $form->field($model, 'slug')->textInput(['maxlength' => true]) ?></div>
      </div>
      <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'body')->widget(CKEditor::class, [
                'editorOptions' => ElFinder::ckeditorOptions('admin/elfinder', [
                    'preset' => 'full',
                    'extraAllowedContent' => ['span', 'p[*]', 'a[*]', 'i[*]', 'video[*]', 'source[*]', '*(*){*}']
                ]),
            ]) ?>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
            <?= $model->thumbnail_path ? Html::img($model->thumbnail_path) : Html::img('/img/no-image.png') ?>
            <?= $form->field($model, 'thumbnail_path')->widget(InputFile::class, [
                'controller' => 'admin/elfinder',
                'filter' => 'image',
                'template' => '<div class="input-group">{input}<span class="input-group-btn">{button}</span></div>',
                'buttonOptions' => ['class' => 'btn btn-default'],
                'multiple' => false
            ]); ?></div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
              <?= $form->field($model, 'status')->widget(ButtonGroup::class, [
                  'default' => 1,
                  'items' => [
                      ['label' => 'Да', 'value' => 1],
                      ['label' => 'Нет', 'value' => 0],
                  ]
              ])->label(null, ['style' => 'display: block']) ?>
          </div>
        </div>
      </div>
    </div>
  </div>
    <?php ActiveForm::end(); ?>
</div>

modules/admin/views/article/create.php
<?php

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Article */
/* @var $categories array */

$this->title = 'Создание статьи';
$this->params['breadcrumbs'][] = ['label' => 'Статьи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-create">

    <?= $this->render('_form', [
        'model' => $model,
        'categories' => $categories
    ]) ?>

</div>

modules/admin/views/article/index.php
<?php

use app\modules\admin\models\Category;
use app\modules\admin\widgets\GridView;
use yii\helpers\Html;

/**
 * @var $this yii\web\View
 * @var $searchModel \app\modules\admin\models\ArticleSearch
 * @var $dataProvider yii\data\ActiveDataProvider
 * @var $categories array
 */

$this->title = 'Статьи';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="content-index">
  <div class="panel panel-default">
    <div class="panel-heading">
        <?= Html::a('Создать статью', ['create'], ['class' => 'btn btn-success']) ?>
    </div>
    <div class="panel-body">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                [
                    'format' => 'raw',
                    'attribute' => 'title',
                    'value' => function ($model) {
                        return Html::a($model->title, ['article/update', 'id' => $model->id]);
                    }
                ],
                [
                    'format' => 'raw',
                    'attribute' => 'slug',
                    'value' => function ($model) {
                        return '<span class="text-light">/page/</span>' . $model->slug;
                    }
                ],
                [
                    'attribute' => 'category_id',
                    'value' => function ($model) {
                        return $model->category ? $model->category->title : '';
                    },
                    'filter' => $categories
                ],
                'author.username:text:Автор',
                [
                    'format' => 'raw',
                    'attribute' => 'status',
                    'headerOptions' => ['width' => 50],
                    'contentOptions' => ['class' => 'text-center'],
                    'value' => function ($model) {
                        return $model->status
                            ? '<span class="label label-success">Да</span>'
                            : '<span class="label label-danger">Нет</span>';
                    },
                    'filter' => ['Нет', 'Да']
                ],
                [
                    'headerOptions' => ['width' => 150],
                    'attribute' => 'created_at',
                    'value' => function ($model) {
                        return date('d.m.Y H:i', $model->created_at);
                    }
                ]
            ]
        ]); ?>
    </div>
  </div>
</div>

modules/admin/views/article/update.php
<?php

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Article */
/* @var $categories array */

$this->title = 'Редактирование: ' . ' ' . $model->slug;
$this->params['breadcrumbs'][] = ['label' => 'Статьи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->slug, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="article-update">

    <?= $this->render('_form', [
        'model' => $model,
        'categories' => $categories
    ]) ?>

</div>

modules/admin/views/article/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Article */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Статьи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-view">
  <p>
      <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
      <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
          'class' => 'btn btn-danger',
          'data' => [
              'confirm' => 'Are you sure you want to delete this item?',
              'method' => 'post',
          ],
      ]) ?>
  </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'slug',
            'title',
            'body:html',
            'view',
            'category_id',
            'thumbnail_base_url:url',
            'thumbnail_path',
            'author_id',
            'updater_id',
            'status',
            'published_at',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>